apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testappsss
spec:
  metrics:
    - name: testappsss
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argfull.isd.ninja-test.opsmx.net/
          user: admin
          application: test17
          baselineStartTime: "2021-11-03T11:29:46.915Z"
          canaryStartTime: "2021-11-03T11:29:46.915Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: log-17
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "Service1"
          - logTemplateName: multilog 
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "Service2"
          - metricTemplateName: metric 
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
            serviceName: "Service1"
          - metricTemplateName: multimetric 
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
            serviceName: "Service2"
