kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo-newrelic-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: demo-newrelic-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://argoisdfull-uat.ninja-test.opsmx.net/
          application: newrelicapp
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: logg26
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            metricTemplateName: metic282
            metricScopeVariables: "app_key,pod_key"
            baselineMetricScope: "demo-test,{{args.baseline-hash}}"
            canaryMetricScope: "demo-test,{{args.canary-hash}}"
