apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argotest
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: newrelic13
  template:
    metadata:   
      labels:
        app: newrelic13
    spec:
      containers:
        - name: rollouts-demo-exp
          image: docker.io/opsmxdev/issuegen:v3.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 45s }
        - experiment:
            analyses:
              - name : newrelic13
                requiredForCompletion: true
                templateName: metric133
            templates:
              - name: metric133
                specRef: stable
              - name: canary
                specRef: canary
        - setWeight: 50
        - pause: { duration: 45s }
        - experiment:
            analyses:
              - name : newrelic13
                requiredForCompletion: true
                templateName: metric133
            templates:
              - name: metric133
                specRef: stable
              - name: canary
                specRef: canary
