apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          profile: opsmx-profile
          gateUrl: https://argoisdfull-uat.ninja-test.opsmx.net/
          user: admin
          application: multipleservicerollout
          baselineStartTime: "2022-08-20T13:15:00Z"
          lifetimeMinutes: "6"
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: logg26
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"

