apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp1
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argoisdfull-uat.ninja-test.opsmx.net/
          user: admin
          application: test28
          baselineStartTime: "2022-03-08T10:46:00Z"
          canaryStartTime: "2022-03-08T10:46:00Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: splunklog28
            logScopeVariables: " kubernetes.container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"

